'//---------------------------------------------------------------------------
'// Copyright (c) Microsoft Corporation.  All rights reserved.
'// This file is automatically generated.  Please do not edit it directly.
'// File name: D2D1Svg.h
'//---------------------------------------------------------------------------
#pragma once
#include once "AfxD2d1.bi"

' // Forward declarations
type ID2D1SvgAttribute AS ID2D1SvgAttribute_
type ID2D1SvgDocument AS ID2D1SvgDocument_
type ID2D1SvgElement AS ID2D1SvgElement_
type ID2D1SvgPaint AS ID2D1SvgPaint_
type ID2D1SvgStrokeDashArray AS ID2D1SvgStrokeDashArray_
type ID2D1SvgPointCollection AS ID2D1SvgPointCollection_
type ID2D1SvgPathData AS ID2D1SvgPathData_

TYPE D2D1_SVG_PAINT_TYPE AS LONG
enum
   D2D1_SVG_PAINT_TYPE_NONE = 0
   D2D1_SVG_PAINT_TYPE_COLOR = 1
   D2D1_SVG_PAINT_TYPE_CURRENT_COLOR = 2
   D2D1_SVG_PAINT_TYPE_URI = 3
   D2D1_SVG_PAINT_TYPE_URI_NONE = 4
   D2D1_SVG_PAINT_TYPE_URI_COLOR = 5
   D2D1_SVG_PAINT_TYPE_URI_CURRENT_COLOR = 6
   D2D1_SVG_PAINT_TYPE_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_LENGTH_UNITS AS LONG
enum
   D2D1_SVG_LENGTH_UNITS_NUMBER = 0
   D2D1_SVG_LENGTH_UNITS_PERCENTAGE = 1
   D2D1_SVG_LENGTH_UNITS_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_DISPLAY AS LONG
enum
   D2D1_SVG_DISPLAY_INLINE = 0
   D2D1_SVG_DISPLAY_NONE = 1
   D2D1_SVG_DISPLAY_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_VISIBILITY AS LONG
enum
   D2D1_SVG_VISIBILITY_VISIBLE = 0
   D2D1_SVG_VISIBILITY_HIDDEN = 1
   D2D1_SVG_VISIBILITY_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_OVERFLOW AS LONG
enum
   D2D1_SVG_OVERFLOW_VISIBLE = 0
   D2D1_SVG_OVERFLOW_HIDDEN = 1
   D2D1_SVG_OVERFLOW_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_LINE_CAP AS LONG
enum
   D2D1_SVG_LINE_CAP_BUTT = D2D1_CAP_STYLE_FLAT
   D2D1_SVG_LINE_CAP_SQUARE = D2D1_CAP_STYLE_SQUARE
   D2D1_SVG_LINE_CAP_ROUND = D2D1_CAP_STYLE_ROUND
   D2D1_SVG_LINE_CAP_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_LINE_JOIN AS LONG
enum
   D2D1_SVG_LINE_JOIN_BEVEL = D2D1_LINE_JOIN_BEVEL
   D2D1_SVG_LINE_JOIN_MITER = D2D1_LINE_JOIN_MITER_OR_BEVEL
   D2D1_SVG_LINE_JOIN_ROUND = D2D1_LINE_JOIN_ROUND
   D2D1_SVG_LINE_JOIN_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_ASPECT_ALIGN AS LONG
enum
   D2D1_SVG_ASPECT_ALIGN_NONE = 0
   D2D1_SVG_ASPECT_ALIGN_X_MIN_Y_MIN = 1
   D2D1_SVG_ASPECT_ALIGN_X_MID_Y_MIN = 2
   D2D1_SVG_ASPECT_ALIGN_X_MAX_Y_MIN = 3
   D2D1_SVG_ASPECT_ALIGN_X_MIN_Y_MID = 4
   D2D1_SVG_ASPECT_ALIGN_X_MID_Y_MID = 5
   D2D1_SVG_ASPECT_ALIGN_X_MAX_Y_MID = 6
   D2D1_SVG_ASPECT_ALIGN_X_MIN_Y_MAX = 7
   D2D1_SVG_ASPECT_ALIGN_X_MID_Y_MAX = 8
   D2D1_SVG_ASPECT_ALIGN_X_MAX_Y_MAX = 9
   D2D1_SVG_ASPECT_ALIGN_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_ASPECT_SCALING AS LONG
enum
   D2D1_SVG_ASPECT_SCALING_MEET = 0
   D2D1_SVG_ASPECT_SCALING_SLICE = 1
   D2D1_SVG_ASPECT_SCALING_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_PATH_COMMAND AS LONG
enum
   D2D1_SVG_PATH_COMMAND_CLOSE_PATH = 0
   D2D1_SVG_PATH_COMMAND_MOVE_ABSOLUTE = 1
   D2D1_SVG_PATH_COMMAND_MOVE_RELATIVE = 2
   D2D1_SVG_PATH_COMMAND_LINE_ABSOLUTE = 3
   D2D1_SVG_PATH_COMMAND_LINE_RELATIVE = 4
   D2D1_SVG_PATH_COMMAND_CUBIC_ABSOLUTE = 5
   D2D1_SVG_PATH_COMMAND_CUBIC_RELATIVE = 6
   D2D1_SVG_PATH_COMMAND_QUADRADIC_ABSOLUTE = 7
   D2D1_SVG_PATH_COMMAND_QUADRADIC_RELATIVE = 8
   D2D1_SVG_PATH_COMMAND_ARC_ABSOLUTE = 9
   D2D1_SVG_PATH_COMMAND_ARC_RELATIVE = 10
   D2D1_SVG_PATH_COMMAND_HORIZONTAL_ABSOLUTE = 11
   D2D1_SVG_PATH_COMMAND_HORIZONTAL_RELATIVE = 12
   D2D1_SVG_PATH_COMMAND_VERTICAL_ABSOLUTE = 13
   D2D1_SVG_PATH_COMMAND_VERTICAL_RELATIVE = 14
   D2D1_SVG_PATH_COMMAND_CUBIC_SMOOTH_ABSOLUTE = 15
   D2D1_SVG_PATH_COMMAND_CUBIC_SMOOTH_RELATIVE = 16
   D2D1_SVG_PATH_COMMAND_QUADRADIC_SMOOTH_ABSOLUTE = 17
   D2D1_SVG_PATH_COMMAND_QUADRADIC_SMOOTH_RELATIVE = 18
   D2D1_SVG_PATH_COMMAND_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_UNIT_TYPE AS LONG
enum
   D2D1_SVG_UNIT_TYPE_USER_SPACE_ON_USE = 0
   D2D1_SVG_UNIT_TYPE_OBJECT_BOUNDING_BOX = 1
   D2D1_SVG_UNIT_TYPE_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_ATTRIBUTE_STRING_TYPE AS LONG
enum
   D2D1_SVG_ATTRIBUTE_STRING_TYPE_SVG = 0
   D2D1_SVG_ATTRIBUTE_STRING_TYPE_ID = 1
   D2D1_SVG_ATTRIBUTE_STRING_TYPE_FORCE_DWORD = &hffffffff
end enum

TYPE D2D1_SVG_ATTRIBUTE_POD_TYPE AS LONG
enum
   D2D1_SVG_ATTRIBUTE_POD_TYPE_FLOAT = 0
   D2D1_SVG_ATTRIBUTE_POD_TYPE_COLOR = 1
   D2D1_SVG_ATTRIBUTE_POD_TYPE_FILL_MODE = 2
   D2D1_SVG_ATTRIBUTE_POD_TYPE_DISPLAY = 3
   D2D1_SVG_ATTRIBUTE_POD_TYPE_OVERFLOW = 4
   D2D1_SVG_ATTRIBUTE_POD_TYPE_LINE_CAP = 5
   D2D1_SVG_ATTRIBUTE_POD_TYPE_LINE_JOIN = 6
   D2D1_SVG_ATTRIBUTE_POD_TYPE_VISIBILITY = 7
   D2D1_SVG_ATTRIBUTE_POD_TYPE_MATRIX = 8
   D2D1_SVG_ATTRIBUTE_POD_TYPE_UNIT_TYPE = 9
   D2D1_SVG_ATTRIBUTE_POD_TYPE_EXTEND_MODE = 10
   D2D1_SVG_ATTRIBUTE_POD_TYPE_PRESERVE_ASPECT_RATIO = 11
   D2D1_SVG_ATTRIBUTE_POD_TYPE_VIEWBOX = 12
   D2D1_SVG_ATTRIBUTE_POD_TYPE_LENGTH = 13
   D2D1_SVG_ATTRIBUTE_POD_TYPE_FORCE_DWORD = &hffffffff
end enum

type D2D1_SVG_LENGTH
   AS FLOAT value
   AS D2D1_SVG_LENGTH_UNITS units
end type

type D2D1_SVG_PRESERVE_ASPECT_RATIO
   AS BOOL defer
   AS D2D1_SVG_ASPECT_ALIGN align
   AS D2D1_SVG_ASPECT_SCALING meetOrSlice
end type

type D2D1_SVG_VIEWBOX
   AS FLOAT x
   AS FLOAT y
   AS FLOAT width
   AS FLOAT height
end type


' ########################################################################################
' Interface name: ID2D1SvgAttribute
' IID: {C9CDB0DD-F8C9-4E70-B7C2-301C80292C5E}
' Inherited interface = ID2D1Resource
' ########################################################################################

DIM SHARED IID_ID2D1SvgAttribute AS GUID = (&hC9CDB0DD, &hF8C9, &h4E70, {&hB7, &hC2, &h30, &h1C, &h80, &h29, &h2C, &h5E})

#ifndef __ID2D1SvgAttribute_INTERFACE_DEFINED__
#define __ID2D1SvgAttribute_INTERFACE_DEFINED__

TYPE ID2D1SvgAttribute_ EXTENDS ID2D1Resource
   DECLARE ABSTRACT SUB GetElement (BYREF svgelement AS ID2D1SvgElement PTR)
   DECLARE ABSTRACT FUNCTION Clone (BYREF attribute AS ID2D1SvgAttribute PTR) AS HRESULT
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgPaint
' IID: {D59BAB0A-68A2-455B-A5DC-9EB2854E2490}
' Inherited interface = ID2D1SvgAttribute
' ########################################################################################

DIM SHARED IID_ID2D1SvgPaint AS GUID = (&hD59BAB0A, &h68A2, &h455B, {&hA5, &hDC, &h9E, &hB2, &h85, &h4E, &h24, &h90})

#ifndef __ID2D1SvgPaint_INTERFACE_DEFINED__
#define __ID2D1SvgPaint_INTERFACE_DEFINED__

TYPE ID2D1SvgPaint_ EXTENDS ID2D1SvgAttribute
   DECLARE ABSTRACT FUNCTION SetPaintType (BYVAL paintType AS D2D1_SVG_PAINT_TYPE) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetPaintType () AS D2D1_SVG_PAINT_TYPE
   DECLARE ABSTRACT FUNCTION SetColor (BYREF color AS D2D1_COLOR_F) AS HRESULT
   DECLARE ABSTRACT SUB GetColor (BYREF color AS D2D1_COLOR_F)
   DECLARE ABSTRACT FUNCTION SetId (BYREF id AS WSTRING) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetId (BYREF id AS WSTRING, BYVAL idCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetIdLength () AS UINT32
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgStrokeDashArray
' IID: {F1C0CA52-92A3-4F00-B4CE-F35691EFD9D9}
' Inherited interface = ID2D1SvgAttribute
' ########################################################################################

DIM SHARED IID_ID2D1SvgStrokeDashArray AS GUID = (&hF1C0CA52, &h92A3, &h4F00, {&hB4, &hCE, &hF3, &h56, &h91, &hEF, &hD9, &hD9})

#ifndef __ID2D1SvgStrokeDashArray_INTERFACE_DEFINED__
#define __ID2D1SvgStrokeDashArray_INTERFACE_DEFINED__

TYPE ID2D1SvgStrokeDashArray_ EXTENDS ID2D1SvgAttribute
   DECLARE ABSTRACT FUNCTION RemoveDashesAtEnd (BYVAL dashesCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION UpdateDashes (BYREF dashes AS const FLOAT, BYVAL dashesCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION UpdateDashes2 (BYREF dashes AS const D2D1_SVG_LENGTH, BYVAL dashesCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetDashes (BYREF dashes AS FLOAT, BYVAL dashesCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetDashes2 (BYREF dashes AS D2D1_SVG_LENGTH, BYVAL dashesCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetDashesCount () AS UINT32
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgPointCollection
' IID: {9DBE4C0D-3572-4DD9-9825-5530813BB712}
' Inherited interface = ID2D1SvgAttribute
' ########################################################################################

DIM SHARED IID_ID2D1SvgPointCollection AS GUID = (&h9DBE4C0D, &h3572, &h4DD9, {&h98, &h25, &h55, &h30, &h81, &h3B, &hB7, &h12})

#ifndef __ID2D1SvgPointCollection_INTERFACE_DEFINED__
#define __ID2D1SvgPointCollection_INTERFACE_DEFINED__

TYPE ID2D1SvgPointCollection_ EXTENDS ID2D1SvgAttribute
   DECLARE ABSTRACT FUNCTION RemovePointsAtEnd (BYVAL pointsCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION UpdatePoints (BYREF points AS const D2D1_POINT_2F, BYVAL pointsCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetPoints (BYREF points AS D2D1_POINT_2F, BYVAL pointsCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetPointsCount () AS UINT32
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgPathData
' IID: {C095E4F4-BB98-43D6-9745-4D1B84EC9888}
' Inherited interface = ID2D1SvgAttribute
' ########################################################################################

DIM SHARED IID_ID2D1SvgPathData AS GUID = (&hC095E4F4, &hBB98, &h43D6, {&h97, &h45, &h4D, &h1B, &h84, &hEC, &h98, &h88})

#ifndef __ID2D1SvgPathData_INTERFACE_DEFINED__
#define __ID2D1SvgPathData_INTERFACE_DEFINED__

TYPE ID2D1SvgPathData_ EXTENDS ID2D1SvgAttribute
   DECLARE ABSTRACT FUNCTION RemoveSegmentDataAtEnd (BYVAL dataCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION UpdateSegmentData (BYREF data AS const FLOAT, BYVAL dataCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetSegmentData (BYREF data AS FLOAT, BYVAL dataCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetSegmentDataCount () AS UINT32
   DECLARE ABSTRACT FUNCTION RemoveCommandsAtEnd (BYVAL commandsCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION UpdateCommands (BYREF commands AS const D2D1_SVG_PATH_COMMAND, BYVAL commandsCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetCommands (BYREF commands AS D2D1_SVG_PATH_COMMAND, BYVAL commandsCount AS UINT32, BYVAL startIndex AS UINT32 = 0) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetCommandsCount () AS UINT32
   DECLARE ABSTRACT FUNCTION CreatePathGeometry (BYVAL fillMode AS D2D1_FILL_MODE, BYREF pathGeometry AS ID2D1PathGeometry1 PTR) AS HRESULT
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgElement
' IID: {AC7B67A6-183E-49C1-A823-0EBE40B0DB29}
' Inherited interface = ID2D1Resource
' Number of methods = 30
' ########################################################################################

DIM SHARED IID_ID2D1SvgElement AS GUID = (&hAC7B67A6, &h183E, &h49C1, {&hA8, &h23, &h0E, &hBE, &h40, &hB0, &hDB, &h29})

#ifndef __ID2D1SvgElement_INTERFACE_DEFINED__
#define __ID2D1SvgElement_INTERFACE_DEFINED__

TYPE ID2D1SvgElement_ EXTENDS ID2D1Resource
   DECLARE ABSTRACT SUB GetDocument (BYREF document AS ID2D1SvgDocument PTR)
   DECLARE ABSTRACT FUNCTION GetTagName (BYREF wszName AS WSTRING, BYVAL nameCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetTagNameLength () AS UINT32
   DECLARE ABSTRACT FUNCTION IsTextContent () AS BOOLEAN
   DECLARE ABSTRACT SUB GetParent (BYREF parent AS ID2D1SvgElement PTR)
   DECLARE ABSTRACT FUNCTION HasChildren () AS BOOLEAN
   DECLARE ABSTRACT SUB GetFirstChild (BYREF child AS ID2D1SvgElement PTR)
   DECLARE ABSTRACT SUB GetLastChild (BYREF child AS ID2D1SvgElement PTR)
   DECLARE ABSTRACT FUNCTION GetPreviousChild (BYVAL referenceChild AS ID2D1SvgElement PTR, BYREF previousChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetNextChild (BYVAL referenceChild AS ID2D1SvgElement PTR, BYREF nextChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION InsertChildBefore (BYVAL newChild AS ID2D1SvgElement PTR, BYVAL referenceChild AS ID2D1SvgElement PTR = NULL) AS HRESULT
   DECLARE ABSTRACT FUNCTION AppendChild (BYVAL newChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION ReplaceChild (BYVAL newChild AS ID2D1SvgElement PTR, BYVAL oldChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION RemoveChild (BYVAL oldChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION CreateChild (BYREF tagName AS WSTRING, BYREF newChild AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION IsAttributeSpecified (BYREF name AS WSTRING, BYREF inherited AS BOOLEAN) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetSpecifiedAttributeCount () AS UINT32
   DECLARE ABSTRACT FUNCTION GetSpecifiedAttributeName (BYVAL index AS UINT32, BYREF name AS WSTRING, BYVAL nameCount AS UINT32, BYREF inherited AS BOOLEAN = FALSE) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetSpecifiedAttributeNameLength (BYVAL index AS UINT32, BYREF nameLength AS UINT32, BYVAL inherited AS BOOLEAN = FALSE) AS HRESULT
   DECLARE ABSTRACT FUNCTION RemoveAttribute (BYREF name AS WSTRING) AS HRESULT
   DECLARE ABSTRACT FUNCTION SetTextValue (BYREF name AS const WSTRING, BYVAL nameCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetTextValue (BYREF name AS WSTRING, BYVAL nameCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetTextValueLength () AS UINT32
   DECLARE ABSTRACT FUNCTION SetAttributeValue (BYREF name AS WSTRING, BYVAL nType AS D2D1_SVG_ATTRIBUTE_POD_TYPE, BYREF value AS WSTRING) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetAttributeValue (BYREF name AS WSTRING, BYVAL nType AS D2D1_SVG_ATTRIBUTE_POD_TYPE, BYREF value AS WSTRING, BYVAL valueCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetAttributeValueLength (BYREF name AS WSTRING, BYVAL nType AS D2D1_SVG_ATTRIBUTE_STRING_TYPE, BYVAL valueLength AS UINT32 PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION SetAttributeValue2 (BYREF name AS WSTRING, BYVAL nType AS D2D1_SVG_ATTRIBUTE_POD_TYPE, BYVAL value AS const ANY PTR, BYVAL valueSizeInBytes AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetAttributeValue2 (BYREF name AS WSTRING, BYVAL nType AS D2D1_SVG_ATTRIBUTE_POD_TYPE, BYVAL value AS ANY PTR, BYVAL valueCount AS UINT32) AS HRESULT
   DECLARE ABSTRACT FUNCTION SetAttributeValue3 (BYREF name AS WSTRING, BYVAL value AS ID2D1SvgAttribute PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION GetAttributeValue3 (BYREF name AS WSTRING, BYREF riid AS IID, BYVAL value AS ANY PTR) AS HRESULT
END TYPE

#endif

' ########################################################################################

' ########################################################################################
' Interface name: ID2D1SvgDocument
' IID: {86B88E4D-AFA4-4D7B-88E4-68A51C4A0AEC}
' Inherited interface = ID2D1Resource
' ########################################################################################

DIM SHARED IID_ID2D1SvgDocument AS GUID = (&h86B88E4D, &hAFA4, &h4D7B, {&h88, &hE4, &h68, &hA5, &h1C, &h4A, &h0A, &hEC})

#ifndef __ID2D1SvgDocument_INTERFACE_DEFINED__
#define __ID2D1SvgDocument_INTERFACE_DEFINED__

TYPE ID2D1SvgDocument_ EXTENDS ID2D1Resource
   DECLARE ABSTRACT FUNCTION SetViewportSize (BYVAL viewportSize AS D2D1_SIZE_F) AS HRESULT
'   DECLARE ABSTRACT FUNCTION GetViewportSize () AS D2D1_SIZE_F
   DECLARE ABSTRACT SUB GetViewportSize (BYREF viewportSize AS D2D1_SIZE_F)
   DECLARE ABSTRACT FUNCTION SetRoot (BYVAL root AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT SUB GetRoot (BYREF root AS ID2D1SvgElement PTR)
   DECLARE ABSTRACT FUNCTION FindElementById (BYREF id AS WSTRING, BYREF svgelement AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION Serialize (BYVAL outputXmlStream AS IStream PTR, BYVAL subtree AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION Deserialize (BYVAL inputXmlStream AS IStream PTR, BYREF subtree AS ID2D1SvgElement PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION CreatePaint (BYVAL paintType AS D2D1_SVG_PAINT_TYPE, BYREF color AS D2D1_COLOR_F, BYREF id AS WSTRING, BYREF paint AS ID2D1SvgPaint PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION CreateStrokeDashArray (BYREF dashes AS D2D1_SVG_LENGTH, BYVAL dashesCount AS UINT32, BYREF strokeDashArray AS ID2D1SvgStrokeDashArray PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION CreatePointCollection (BYREF points AS const D2D1_POINT_2F, BYVAL pointsCount AS UINT32, BYREF pointCollection AS ID2D1SvgPointCollection PTR) AS HRESULT
   DECLARE ABSTRACT FUNCTION CreatePathData (BYREF segmentData AS FLOAT, BYVAL segmentDataCount AS UINT32, BYREF commands AS const D2D1_SVG_PATH_COMMAND, BYVAL commandsCount AS UINT32, BYREF pathData AS ID2D1SvgPathData PTR) AS HRESULT
END TYPE

#endif

' ########################################################################################
